#################################################################################
##                                                                             ##
##          M  a  k  e  f  i  l  e  .  m  p  i  c  h                           ##
##                                                                             ##
##   Make include file for compiler and os specific settings                   ##
##   Compile and link options for Gnu compiler gcc                             ##
##   Parallel MPI is enabled using MPICH                                       ##
##                                                                             ##
## (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file ##
## authors, and contributors see AUTHORS file                                  ##
## This file is part of LPJmL and licensed under GNU AGPL Version 3            ##
## or later. See LICENSE file or go to http://www.gnu.org/licenses/            ##
## Contact: https://github.com/PIK-LPJmL/LPJmL                                 ##
##                                                                             ##
#################################################################################

CC	= mpicc
DEBUGFLAGS  = -g
CHECKFLAGS = -fsanitize=address -fsanitize=bounds -fsanitize=undefined
# -fno-math-errno lets the compiler treat the libm calls as the pure
# functions they are. It does not change any computed value -- only whether
# errno is set -- and it is what allows dead and duplicated calls to be
# removed. Verified byte-identical on a full-grid run.
OPTFLAGS= -O3 -fno-math-errno
WFLAG	= -Wall -m64
LPJFLAGS  = -DUSE_RAND48 -DUSE_MPI -DSAFE -DWITH_FPE -DUSE_NETCDF -DUSE_UDUNITS -DPERMUTE -DSTRICT_JSON
O	= o
A	= a
E	=
AR	= ar
ARFLAGS	= r 
RM	= rm 
RMFLAGS	= -f
LIBS	= -lm -lnetcdf -ludunits2 -ljson-c
LINKMAIN= mpicc
LINK	= gcc -m64
MKDIR	= mkdir -p
SLASH	= /
