/**************************************************************************************/
/**                                                                                \n**/
/**                        m  a  n  a  g  e  p  a  r  .  h                         \n**/
/**                                                                                \n**/
/**     C implementation of LPJmL                                                  \n**/
/**                                                                                \n**/
/**     Country codes for management practices                                     \m**/
/**                                                                                \n**/
/** (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file    \n**/
/** authors, and contributors see AUTHORS file                                     \n**/
/** This file is part of LPJmL and licensed under GNU AGPL Version 3               \n**/
/** or later. See LICENSE file or go to http://www.gnu.org/licenses/               \n**/
/** Contact: https://github.com/PIK-LPJmL/LPJmL                                    \n**/
/**                                                                                \n**/
/**************************************************************************************/

#ifndef MANAGEPAR_H /* Already included? */
#define MANAGEPAR_H

/* Definition of country-codes*/
/* Definition of region-codes*/

#define Aruba 0
#define Afghanistan 1
#define Angola 2
#define Anguilla 3
#define Aland 4
#define Albania 5
#define Andorra 6
#define United_Arab_Emirates 7
#define Argentina 8
#define Armenia 9
#define American_Samoa 10
#define Antarctica 11
#define French_Southern_Territories 12
#define Antigua_and_Barbuda 13
#define Austria 14
#define Azerbaijan 15
#define Burundi 16
#define Belgium 17
#define Benin 18
#define Bonaire_Sint_Eustatius_and_Saba 19
#define Burkina_Faso 20
#define Bangladesh 21
#define Bulgaria 22
#define Bahrain 23
#define Bahamas 24
#define Bosnia_and_Herzegovina 25
#define Saint_Barthelemy 26
#define Belarus 27
#define Belize 28
#define Bermuda 29
#define Bolivia 30
#define Barbados 31
#define Brunei 32
#define Bhutan 33
#define Bouvet_Island 34
#define Botswana 35
#define Central_African_Republic 36
#define Cocos_Islands 37
#define Switzerland 38
#define Chile 39
#define Cote_Ivoire 40
#define Cameroon 41
#define Democratic_Republic_of_the_Congo 42
#define Republic_of_Congo 43
#define Cook_Islands 44
#define Colombia 45
#define Comoros 46
#define Cape_Verde 47
#define Costa_Rica 48
#define Cuba 49
#define Curacao 50
#define Christmas_Island 51
#define Cayman_Islands 52
#define Cyprus 53
#define Czech_Republic 54
#define Germany 55
#define Djibouti 56
#define Dominica 57
#define Denmark 58
#define Dominican_Republic 59
#define Algeria 60
#define Ecuador 61
#define Egypt 62
#define Eritrea 63
#define Western_Sahara 64
#define Spain 65
#define Estonia 66
#define Ethiopia 67
#define Finland 68
#define Fiji 69
#define Falkland_Islands 70
#define France 71
#define Faroe_Islands 72
#define Micronesia 73
#define Gabon 74
#define United_Kingdom 75
#define Georgia 76
#define Guernsey 77
#define Ghana 78
#define Gibraltar 79
#define Guinea 80
#define Guadeloupe 81
#define Gambia 82
#define Guinea_Bissau 83
#define Equatorial_Guinea 84
#define Greece 85
#define Grenada 86
#define Greenland 87
#define Guatemala 88
#define French_Guiana 89
#define Guam 90
#define Guyana 91
#define Hong_Kong 92
#define Heard_Island_and_McDonald_Islands 93
#define Honduras 94
#define Croatia 95
#define Haiti 96
#define Hungary 97
#define Indonesia 98
#define Isle_of_Man 99
#define British_Indian_Ocean_Territory 100
#define Ireland 101
#define Iran 102
#define Iraq 103
#define Iceland 104
#define Israel 105
#define Italy 106
#define Jamaica 107
#define Jersey 108
#define Jordan 109
#define Japan 110
#define Kazakhstan 111
#define Kenya 112
#define Kyrgyzstan 113
#define Cambodia 114
#define Kiribati 115
#define Saint_Kitts_and_Nevis 116
#define South_Korea 117
#define Kuwait 118
#define Laos 119
#define Lebanon 120
#define Liberia 121
#define Libya 122
#define Saint_Lucia 123
#define Liechtenstein 124
#define Sri_Lanka 125
#define Lesotho 126
#define Lithuania 127
#define Luxembourg 128
#define Latvia 129
#define Macao 130
#define Saint_Martin 131
#define Morocco 132
#define Monaco 133
#define Moldova 134
#define Madagascar 135
#define Maldives 136
#define Mexico 137
#define Marshall_Islands 138
#define Macedonia 139
#define Mali 140
#define Malta 141
#define Myanmar 142
#define Montenegro 143
#define Mongolia 144
#define Northern_Mariana_Islands 145
#define Mozambique 146
#define Mauritania 147
#define Montserrat 148
#define Martinique 149
#define Mauritius 150
#define Malawi 151
#define Malaysia 152
#define Mayotte 153
#define Namibia 154
#define New_Caledonia 155
#define Niger 156
#define Norfolk_Island 157
#define Nigeria 158
#define Nicaragua 159
#define Niue 160
#define Netherlands 161
#define Norway 162
#define Nepal 163
#define Nauru 164
#define New_Zealand 165
#define Oman 166
#define Pakistan 167
#define Panama 168
#define Pitcairn_Islands 169
#define Peru 170
#define Philippines 171
#define Palau 172
#define Papua_New_Guinea 173
#define Poland 174
#define Puerto_Rico 175
#define North_Korea 176
#define Portugal 177
#define Paraguay 178
#define Palestina 179
#define French_Polynesia 180
#define Qatar 181
#define Reunion 182
#define Romania 183
#define Rwanda 184
#define Saudi_Arabia 185
#define Sudan 186
#define Senegal 187
#define Singapore 188
#define South_Georgia_and_the_South_Sandwich_Islands 189
#define Saint_Helena 190
#define Svalbard 191
#define Solomon_Islands 192
#define Sierra_Leone 193
#define El_Salvador 194
#define San_Marino 195
#define Somalia 196
#define Saint_Pierre_and_Miquelon 197
#define Serbia 198
#define South_Sudan 199
#define Sao_Tome_and_Principe 200
#define Suriname 201
#define Slovakia 202
#define Slovenia 203
#define Sweden 204
#define Swaziland 205
#define Sint_Maarten 206
#define Seychelles 207
#define Syria 208
#define Turks_and_Caicos_Islands 209
#define Chad 210
#define Togo 211
#define Thailand 212
#define Tajikistan 213
#define Tokelau 214
#define Turkmenistan 215
#define Timor_Leste 216
#define Tonga 217
#define Trinidad_and_Tobago 218
#define Tunisia 219
#define Turkey 220
#define Tuvalu 221
#define Taiwan 222
#define Tanzania 223
#define Uganda 224
#define Ukraine 225
#define United_States_Minor_Outlying_Islands 226
#define Uruguay 227
#define Uzbekistan 228
#define Vatican_City 229
#define Saint_Vincent_and_the_Grenadines 230
#define Venezuela 231
#define British_Virgin_Islands 232
#define US_Virgin_Islands 233
#define Vietnam 234
#define Vanuatu 235
#define Wallis_and_Futuna 236
#define Samoa 237
#define Yemen 238
#define South_Africa 239
#define Zambia 240
#define Zimbabwe 241
#define Akrotiri_and_Dhekelia 242
#define Caspian_Sea 243
#define Clipperton_Island 244
#define Kosovo 245
#define Northern_Cyprus 246
#define Paracel_Islands 247
#define Spratly_Islands 248

#define No_land 249
#define Australia 250
#define Brazil 251
#define Canada 252
#define China 253
#define India 254
#define Russia 255
#define United_States 256

#endif
